gate: graph-integrity
phase_transition: "1→2"
required: true
description: "Validates semantic knowledge graph integrity and completeness"

checks:
  - name: "graph_file_exists"
    type: "file_exists"
    severity: "error"
    description: "graph.json must exist in corpus"
    file: ".project/corpus/graph.json"

  - name: "adjacency_file_exists"
    type: "file_exists"
    severity: "error"
    description: "adjacency.json must exist in corpus"
    file: ".project/corpus/adjacency.json"

  - name: "min_nodes"
    type: "json_path"
    severity: "warning"
    description: "Graph should have at least 3 nodes for meaningful analysis"
    file: ".project/corpus/graph.json"
    json_path: "$.metadata.node_count"
    operator: ">="
    value: 3

  - name: "min_edges"
    type: "json_path"
    severity: "warning"
    description: "Graph should have at least 1 edge for semantic relations"
    file: ".project/corpus/graph.json"
    json_path: "$.metadata.edge_count"
    operator: ">="
    value: 1

  - name: "graph_valid_json"
    type: "json_valid"
    severity: "error"
    description: "graph.json must be valid JSON"
    file: ".project/corpus/graph.json"

  - name: "adjacency_valid_json"
    type: "json_valid"
    severity: "error"
    description: "adjacency.json must be valid JSON"
    file: ".project/corpus/adjacency.json"

  - name: "graph_has_version"
    type: "json_path"
    severity: "error"
    description: "graph.json must have version field"
    file: ".project/corpus/graph.json"
    json_path: "$.version"
    operator: "exists"

  - name: "adjacency_matches_graph"
    type: "custom"
    severity: "error"
    description: "Adjacency node count must match graph node count"
    script: |
      import json
      from pathlib import Path

      corpus_dir = Path(".project/corpus")
      with open(corpus_dir / "graph.json") as f:
          graph = json.load(f)
      with open(corpus_dir / "adjacency.json") as f:
          adjacency = json.load(f)

      graph_nodes = graph['metadata']['node_count']
      adjacency_nodes = len(adjacency['adjacency'])

      if graph_nodes != adjacency_nodes:
          raise ValueError(f"Node count mismatch: graph={graph_nodes}, adjacency={adjacency_nodes}")

automation:
  on_failure:
    - action: "log"
      message: "Graph integrity check failed. Review corpus structure."

  on_success:
    - action: "log"
      message: "Graph integrity validated successfully"
