#!/usr/bin/env python3
"""
copilot-cloud-agent dispatcher.

Walks .specify/specs/<slug>/tasks/TASK-NNN-*.md, filters by
``parallelization_hint: copilot_cloud_agent``, creates a GitHub issue
per task with the story-context document as body, and assigns @copilot.

This script is the natural-language-preserving shim: all the *meaning*
lives in the markdown task files. The script only handles the side
effects (gh CLI calls, mapping file writes, secret scan).

Usage:
  python3 dispatcher.py --spec-slug pix-checkout [--dry-run]
                        [--tasks TASK-001,TASK-003]
                        [--max-parallel 5]
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
MAPPING_FILE = REPO_ROOT / ".project" / "issue-mapping.yml"

SECRET_PATTERNS = [
    re.compile(r"(?i)(api[_-]?key|secret|token|password|private[_-]?key)\s*[:=]"),
    re.compile(r"-----BEGIN [A-Z ]+ PRIVATE KEY-----"),
    re.compile(r"ghp_[A-Za-z0-9]{36}"),  # GitHub token
    re.compile(r"xox[baprs]-[A-Za-z0-9-]{10,}"),  # Slack
    re.compile(r"AIza[0-9A-Za-z\-_]{35}"),  # Google
]


@dataclass
class TaskFile:
    task_id: str
    path: Path
    frontmatter: dict[str, Any] = field(default_factory=dict)
    body: str = ""

    @property
    def hint(self) -> str:
        return str(self.frontmatter.get("parallelization_hint", "human_only"))

    @property
    def assignee(self) -> str:
        return str(self.frontmatter.get("assignee", "unassigned"))

    @property
    def status(self) -> str:
        return str(self.frontmatter.get("status", "ready"))


def parse_task_file(path: Path) -> TaskFile:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.DOTALL)
    if not m:
        raise ValueError(f"{path}: missing YAML frontmatter")
    fm = yaml.safe_load(m.group(1)) or {}
    body = m.group(2).strip()
    task_id = str(fm.get("task_id") or path.stem.split("-")[0])
    return TaskFile(task_id=task_id, path=path, frontmatter=fm, body=body)


def scan_for_secrets(content: str, where: Path) -> list[str]:
    findings: list[str] = []
    for pat in SECRET_PATTERNS:
        if pat.search(content):
            findings.append(f"possible secret matching {pat.pattern!r} in {where}")
    return findings


def preflight(spec_slug: str) -> list[str]:
    errors: list[str] = []
    spec_dir = REPO_ROOT / ".specify" / "specs" / spec_slug
    if not spec_dir.is_dir():
        errors.append(f"spec dir not found: {spec_dir}")
        return errors
    strategy = spec_dir / "strategy.yml"
    if strategy.exists():
        with strategy.open() as f:
            data = yaml.safe_load(f) or {}
        primary = (data.get("strategy") or {}).get("primary")
        if primary != "copilot_cloud_agent":
            errors.append(
                f"strategy.yml primary is {primary!r}, expected "
                f"'copilot_cloud_agent' — refuse to dispatch"
            )
    # gh auth check
    try:
        subprocess.run(
            ["gh", "auth", "status"], check=True, capture_output=True, timeout=10
        )
    except FileNotFoundError:
        errors.append("gh CLI not installed")
    except subprocess.CalledProcessError:
        errors.append("gh auth failed — run `gh auth login`")
    except subprocess.TimeoutExpired:
        errors.append("gh auth timed out")
    return errors


def collect_tasks(spec_slug: str, filter_ids: set[str] | None) -> list[TaskFile]:
    tasks_dir = REPO_ROOT / ".specify" / "specs" / spec_slug / "tasks"
    if not tasks_dir.is_dir():
        return []
    tasks: list[TaskFile] = []
    for p in sorted(tasks_dir.glob("TASK-*.md")):
        try:
            tf = parse_task_file(p)
        except ValueError as exc:
            print(f"WARN: {exc}", file=sys.stderr)
            continue
        if filter_ids and tf.task_id not in filter_ids:
            continue
        tasks.append(tf)
    return tasks


def render_issue_body(task: TaskFile, spec_slug: str) -> str:
    header = (
        "<!-- Generated by copilot-cloud-agent dispatcher — do not edit "
        "the header -->\n\n"
    )
    footer = (
        "\n\n---\n"
        f"**spec**: `.specify/specs/{spec_slug}/spec.md`\n"
        f"**plan**: `.specify/specs/{spec_slug}/plan.md`\n"
        f"**task**: `{task.path.relative_to(REPO_ROOT)}`\n"
        f"**constitution**: v1.0.0 — principles II, III, IV, VII apply\n"
    )
    return header + task.body + footer


def create_issue(
    title: str,
    body: str,
    labels: list[str],
    assignee: str,
    dry_run: bool,
) -> str | None:
    """Returns issue URL on success. None in dry-run."""
    cmd = [
        "gh",
        "issue",
        "create",
        "--title",
        title,
        "--body",
        body,
        "--label",
        ",".join(labels),
    ]
    if assignee and assignee != "unassigned":
        # Strip leading '@' if present; gh expects the login
        cmd.extend(["--assignee", assignee.lstrip("@")])
    if dry_run:
        print("DRY-RUN: would run:", " ".join(repr(c) for c in cmd))
        return None
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    if proc.returncode != 0:
        raise RuntimeError(
            f"gh issue create failed: {proc.stderr.strip() or proc.stdout.strip()}"
        )
    url = proc.stdout.strip().splitlines()[-1]
    return url


def load_mapping() -> dict[str, Any]:
    if not MAPPING_FILE.exists():
        return {"mapping": []}
    with MAPPING_FILE.open() as f:
        return yaml.safe_load(f) or {"mapping": []}


def save_mapping(data: dict[str, Any]) -> None:
    MAPPING_FILE.parent.mkdir(parents=True, exist_ok=True)
    with MAPPING_FILE.open("w") as f:
        yaml.safe_dump(data, f, sort_keys=False)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec-slug", required=True)
    parser.add_argument("--tasks", help="Comma-separated TASK-NNN filter")
    parser.add_argument("--max-parallel", type=int, default=5)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    errors = preflight(args.spec_slug)
    if errors:
        for e in errors:
            print(f"PREFLIGHT FAIL: {e}", file=sys.stderr)
        return 2

    filter_ids = (
        {t.strip() for t in args.tasks.split(",")} if args.tasks else None
    )
    tasks = collect_tasks(args.spec_slug, filter_ids)

    eligible: list[TaskFile] = []
    for t in tasks:
        if t.hint != "copilot_cloud_agent":
            continue
        if t.status not in ("ready", "in_review"):
            continue
        secrets = scan_for_secrets(t.body, t.path)
        if secrets:
            print(
                f"SECRET-SCAN FAIL {t.task_id}: {'; '.join(secrets)}",
                file=sys.stderr,
            )
            return 3
        eligible.append(t)

    eligible = eligible[: args.max_parallel]
    mapping = load_mapping()
    mapping_list = mapping.setdefault("mapping", [])
    created: list[dict[str, Any]] = []

    for t in eligible:
        title = f"[{t.task_id}] {t.frontmatter.get('title', t.task_id)}"
        body = render_issue_body(t, args.spec_slug)
        labels = ["sdlc:auto", "phase:6", "type:task", "dispatch:copilot"]
        assignee = t.assignee or "@copilot"
        try:
            url = create_issue(title, body, labels, assignee, args.dry_run)
        except RuntimeError as exc:
            print(f"DISPATCH FAIL {t.task_id}: {exc}", file=sys.stderr)
            return 4
        entry = {
            "task_id": t.task_id,
            "spec_slug": args.spec_slug,
            "issue_url": url,
            "assignee": assignee,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "dispatcher": "copilot-cloud-agent",
        }
        mapping_list.append(entry)
        created.append(entry)

    if not args.dry_run:
        save_mapping(mapping)

    result = {
        "spec_slug": args.spec_slug,
        "dispatched": len(created),
        "dry_run": args.dry_run,
        "entries": created,
    }
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(f"Dispatched {len(created)} task(s) for {args.spec_slug}")
        for e in created:
            print(f"  {e['task_id']} -> {e.get('issue_url', '<dry-run>')}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
